### ISSUE TITLE
Reproduction on WMT15/16

### ISSUE THREAD

**Issue by cyr19** [PierreColombo/nlg_eval_via_simi_measures#5]
Hi,

thanks for your great work! I'm interested in BaryScore and want to reproduce your results. 
May I know with which human judgments you correlate BaryScore on WMT15? As far as I know, WMT15 officially calculates Kendall's tau with ranking-based human judgments, but you reported three types of correlations, so I guess there should be some human ratings like DA scores. Unfortunately, I was not able to find the DA scores. Could you help me with this? And the link to WMT16 DA judgments on its official website is currently invalid, do you still have this data? Besides, I'm not sure if I did something wrong, but BaryScore runs really slowly on my computer (over 200s for one language pair in WMT15 (BERTScore about 8s)). It seems the code already supports GPU computation?

Thanks a lot!

**Comment by cyr19** [comment]
I see the human scores in the raw_score file. Thanks for releasing them!

**Comment by PierreColombo** [comment]
Thanks for opening the issue. 
Since this is solved. I'll close it.
Best.

**Comment by cyr19** [comment]
Hi,

I still have a question.
I wonder if the code already enables GPU computation? It seems it does, but it runs much more slowly than BERTScore and MoverScore.

Best wishes.

**Comment by PierreColombo** [comment]
Hello,
Thanks for opening the issue.
Can you monitor that the model is loaded on the gpu with nvidia-smi ?
Kindest regards,
Pierre

**Comment by cyr19** [comment]
Hello,

I checked the GPU utilization - it is 0%. It seems some code for GPU compuation is missing.?

Best regards

**Comment by PierreColombo** [comment]
Hi everything should be on device (see l29,l91) with so little information. I am not sure to be of great help. 
The only cpu information is everything relate to OT.

**Comment by cyr19** [comment]
[gpu_usage.csv](https://github.com/PierreColombo/nlg_eval_via_simi_measures/files/8218061/gpu_usage.csv)
Hi 
thanks! 
I attached the GPU usage monitoring file. The GPU is rarely used during the evaluation procedure. I hope this could help.

**Comment by PierreColombo** [comment]
It seems the model is loaded. But OT is not on gpu. If you want to do a faster implementation. You should consider using cupy : https://pythonot.github.io/gen_modules/ot.backend.html?highlight=cupy#ot.backend.CupyBackend. 
But it is not done yet !

**Comment by cyr19** [comment]
I see. Thanks ;)

Best
